### ISSUE TITLE
Soporte de comandos directos al bot

### ISSUE THREAD

**Issue by jcastro** [hectorzin/botaffiumeiro#10]
Poder (como administrador del grupo) solicitar con ciertos comandos datos o funcionalidades, por ejemplo:  
`/descuentos` el bot publica un mensaje con descuentos activos.  
`/producto [nombrepersonalizado]` el bot publica un enlace afiliado de X producto; por ejemplo, `/producto zigbee` publica el enlace del SLZB que tanto nos gusta :D

**Comment by hectorzin** [comment]
yo lo veo más como /product link y que ponga el link de afiliado de eso, no?

porque si se pone zigbeee, a que producto de todos los del mundo zigbee nos vamos?

**Comment by jcastro** [comment]
si.. tienes razón, lo estaba pensando mas como tener una lista de "favoritos" y definir que zigbee = X enlace

**Comment by hectorzin** [comment]
Lo que sería chulo es usar la IA, para que interprete los mensajes, y entonces cuando detecte que alguien parece estar interesado en algo, que le meta un producto, diciendo (este producto está recomendado por una IA, por lo que no se puede considerar que haya sido probado por nadie del grupo, pero ojéalo que igual te podría servir)

lo que diría que la API de chatgpt tiene límite de uso, y claro, si a cada mensaje se le va preguntando.... igual es demasiado, pero estaría genial algo así.

**Comment by jcastro** [comment]
las llamadas a la API de chatgpt son mega baratas... no creo que sea un problema!

**Comment by hectorzin** [comment]
bueno, la parte de descuentos está, hay que hacer una issue por cosa porque si no es un lío para cerrarlas
